title: Dongqi Fu
logo: /assets/img/logo.png
description: "Email: dongqif2 [AT] illinois [DOT] edu Address: Room 113, 501 E. Green St., Champaign, IL 61820"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
